services:
  web:
    build:
      context: ./app/
    env_file:
      - .env.local
    volumes:
      - ./app/:/app/
    ports:
      - 8080:8080

  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/workspace/
      - ~/.ssh:/home/devuser/.ssh:ro
      - ~/.config/gcloud:/home/devuser/.config/gcloud
      - ~/.config/gh:/home/devuser/.config/gh:ro
    command: sleep infinity