services:
  web:
    build:
      context: ./app/
    env_file:
      - .env
    volumes:
      - ./app/:/app/
    ports:
      - 8080:8080

  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/workspace/
      - ~/.ssh:/root/.ssh:ro
    command: sleep infinity