# ABOUTME: Validates pull requests by running tests and building the Flask image.
# ABOUTME: Ensures Docker builds succeed without deploying changes to Cloud Run.
steps:
  - name: 'python:3.11-slim'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        set -u
        python -m pip install --no-cache-dir -r app/requirements.txt
        python -m pip install --no-cache-dir pytest
        status=0
        python -m pytest || status=$?
        if [ "$status" -eq 5 ]; then
          echo "pytest reported no tests; treating as success."
          status=0
        fi
        exit "$status"

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'pr-validation'
      - './app'

options:
  logging: CLOUD_LOGGING_ONLY
