# ABOUTME: Ensures Docker builds succeed for pull requests without running tests.
# ABOUTME: Provides a smoke check that the Flask image is buildable via Cloud Build.
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'pr-validation'
      - './app'

options:
  logging: CLOUD_LOGGING_ONLY
