# ABOUTME: Builds, pushes, and deploys the Flask application to Cloud Run.
# ABOUTME: Runs on main branch pushes using Cloud Build substitutions.
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/flask-app:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/flask-app:latest'
      - './app'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/flask-app:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/flask-app:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/flask-app:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=${_SERVICE_ACCOUNT_EMAIL}'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
