name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt', 'app/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r app/requirements.txt -r app/requirements-dev.txt

      - name: Install Black
        run: |
          BLACK_VERSION=$(python -c "import pathlib, sys
          lines = pathlib.Path('.pre-commit-config.yaml').read_text().splitlines()
          repo_index = next((i for i, line in enumerate(lines) if 'https://github.com/psf/black' in line), -1)
          if repo_index == -1:
              sys.exit('Black repo block not found in .pre-commit-config.yaml')
          version = None
          for line in lines[repo_index + 1:]:
              stripped = line.strip()
              if stripped.startswith('rev:'):
                  raw = stripped.split(':', 1)[1].strip()
                  version = raw.replace('\"', '').replace(\"'\", '')
                  break
              if stripped.startswith('repo:'):
                  break
          if not version:
              sys.exit('Black rev not found in .pre-commit-config.yaml')
          print(version)")
          pip install "black==${BLACK_VERSION}"

      - name: Check formatting
        run: black --check app

      - name: Run tests
        env:
          PYTHONWARNINGS: error
        run: pytest --cov=webapp --cov-report=term-missing
        working-directory: app
